name: Android Instrumentation Tests

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - .github/workflows/android-instrumentation-tests.yml
      - android/**
      - fastlane/**
      # - packages/**/android/**
      - packages/expo-eas-client/android/**
      - packages/expo-json-utils/android/**
      - packages/expo-manifests/android/**
      - packages/expo-updates/android/**
      - yarn.lock
      - '!packages/@expo/cli/**'
  pull_request:
    paths:
      - .github/workflows/android-instrumentation-tests.yml
      - android/**
      - fastlane/**
      # - packages/**/android/**
      - packages/expo-eas-client/android/**
      - packages/expo-json-utils/android/**
      - packages/expo-manifests/android/**
      - packages/expo-updates/android/**
      - yarn.lock
      - '!packages/@expo/cli/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-13
    timeout-minutes: 150
    env:
      ORG_GRADLE_PROJECT_reactNativeArchitectures: x86_64
      GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=1024m
    strategy:
      matrix:
        api-level: [33]
    steps:
      - name: 👀 Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: 🏗️ Setup Expo Tools
        uses: ./.github/actions/setup-expo-tools
        with:
          node-version: 16
      - name: 🔨 Use JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: ♻️ Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
        with:
          gradle: 'true'
          yarn-workspace: 'true'
          hermes-engine-aar: 'true'
          react-native-gradle-downloads: 'true'
      - name: 🧶 Install node modules in root dir
        if: steps.expo-caches.outputs.yarn-workspace-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: 📱 Run instrumented unit tests
        timeout-minutes: 80
        uses: ./.github/actions/use-android-emulator
        with:
          avd-api: ${{ matrix.api-level }}
          avd-name: avd-${{ matrix.api-level }}
          script: expotools android-native-unit-tests --type instrumented
      - name: 💾 Save test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: packages/**/build/outputs/androidTest-results/**/*
